version: '3.8'

services:
  app:
    build:
      context: .
    container_name: transaction-app
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      - mysql
      - mailhog

  mailhog:
    image: mailhog/mailhog
    container_name: mailhog
    ports:
      - "1025:1025" # SMTP port
      - "8025:8025" # Web UI port

  mysql:
    image: mysql:latest
    container_name: transaction-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: transactions_db
    ports:
      - "3306:3306"
    volumes:
      - './migrations/init.sql:/docker-entrypoint-initdb.d/init.sql'